### PR TITLE
RoadSigns preset for Austria

### PR DESCRIPTION
**Pull request by Luzandro**
https://josm.openstreetmap.de/ticket/23586

### CODE REVIEW

**Comment by tsmock** [comment]
As skyper said in #23586, I'd _strongly_ prefer svg icons. The reason for this is so that the images scale better given different display DPIs and sizes.

**Comment by Luzandro** [comment]
There aren't SVG versions for all of the icons and as far as I can see, you can't specify the desired display size of the vector graphics, so I would have to resize the default size for all of the files. I don't know a simple batch way to do this at once. I have resized a few single ones, but somehow it looked a bit off and cropped at the border. Considering that nearly all of the other countries use PNG I decided to stick with that as well and remove the additional SVG files as requested

**Comment by tsmock** [comment]
> you can't specify the desired display size of the vector graphics

JOSM scales the images to a given bounding box internally, so long as the original size was 16x16 or >64x64. This lets us have good-looking icons on HiDPI devices (think "retina display") and low DPI devices.

Sample: https://github.com/JOSM/josm/blob/master/resources/images/presets/service/letter_box.svg?short_path=727054e

Look for `width`, `height`, and `viewBox`.

> remove the additional SVG files as requested

Please don't. That wasn't requested. I specifically _want_ svg icons over png icons. png is a "lossy" format while svg isn't.
Yes, the other countries use png, but have you looked at when those files were added? Hint: it was years ago, prior to JOSM moving to svg for their internal icons.

At the very least, include the source svgs in a nodist directory, e.g. `images_nodist/AT/`.

**Comment by Luzandro** [comment]
managed to resize the svg files appropriately using `rsvg-convert`

**Comment by Luzandro** [comment]
any updates?

**Comment by tsmock** [comment]
In [36316/osm](https://josm.openstreetmap.de/changeset/36316/osm):

Fix [#23586](https://josm.openstreetmap.de/ticket/23586): Add Austria signs in RoadSigns (patch by Luzandro, modified)

Modifications are as follows:
* Update minimum JOSM version to [r19044](https://josm.openstreetmap.de/changeset/19044/osm) since we now build with Java 11.
* Lint cleanup of RoadSignsPlugin.java

**Pull request closed without merging**
